const products = [
  {
    id: "Armod-150",
    name: "Armod 150 MG",
    price: "$100.00 - $640.00",
    image: "../images/armodafinil/armod-150-300x250.webp",
    ingredient: "Armodafinil",
    manufacturer: "Healing Pharma",
    indication: "Cognitive Enhancers",
    strength: "150mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "armodafinil",
    rating: 4.8,
    reviews: 52,
    prescription: true
  },

  {
    id: "Armod-50",
    name: "Armod 50 MG",
    price: "$60.00 - $415.00",
    image: "../images/armodafinil/armod-50-mg-e1632310606672-200x167.webp",
    ingredient: "Armodafinil",
    manufacturer: "Healing Pharma",
    indication: "Cognitive Enhancers",
    strength: "50mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "armodafinil",
    rating: 4.7,
    reviews: 44,
    prescription: true
  },

  {
    id: "Artvigil-150",
    name: "Artvigil 150 MG",
    price: "$345.00 - $765.00",
    image: "../images/armodafinil/Artvigil-150-300x250.webp",
    ingredient: "Armodafinil",
    manufacturer: "HAB Pharma",
    indication: "Cognitive Enhancers",
    strength: "150mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "armodafinil",
    rating: 4.9,
    reviews: 61,
    prescription: true
  },

  {
    id: "Waklert-150",
    name: "Waklert 150 MG",
    price: "$85.00 - $800.00",
    image: "../images/armodafinil/Waklert-150-1-300x250.webp",
    ingredient: "Armodafinil",
    manufacturer: "Sun Pharma",
    indication: "Cognitive Enhancers",
    strength: "150mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "armodafinil",
    rating: 4.9,
    reviews: 73,
    prescription: true
  },

  {
    id: "Waklert-50",
    name: "Waklert 50 MG",
    price: "$60.00 - $499.00",
    image: "../images/armodafinil/waklert-50mg-300x250.webp",
    ingredient: "Armodafinil",
    manufacturer: "Sun Pharma",
    indication: "Cognitive Enhancers",
    strength: "50mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "armodafinil",
    rating: 4.8,
    reviews: 48,
    prescription: true
  },

  {
    id: "Modafresh-200",
    name: "Modafresh 200 Mg",
    price: "$70.00 - $245.00",
    price: "$60.00 - $370.00",
    image: "../images/Modafinil/Modafresh-300x250.webp",
    ingredient: "Modafinil",
    manufacturer: "Actiza Pharmaceutical Pvt. Ltd.",
    indication: "Cognitive Enhancers",
    strength: "200mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "modafinil",
    rating: 4.8,
    reviews: 49,
    prescription: true
},

{
    id: "Modaheal-200",
    name: "Modaheal 200 MG",
    price: "$55.00 - $125.00",
    image: "../images/Modafinil/modaheal-300x250.webp",
    ingredient: "Modafinil",
    manufacturer: "HAB Pharma",
    indication: "Cognitive Enhancers",
    strength: "200mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "modafinil",
    rating: 4.7,
    reviews: 42,
    prescription: true
},

{
    id: "Vilafinil-200",
    name: "Vilafinil 200 MG",
    price: "$50.00 - $280.00",
    image: "../images/Modafinil/Vilafinil-1-300x250.webp",
    ingredient: "Modafinil",
    manufacturer: "Sun Pharma",
    indication: "Cognitive Enhancers",
    strength: "200mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "modafinil",
    rating: 4.9,
    reviews: 63,
    prescription: true
},

{
    id: "Modafinil-200-Australia",
    name: "Modafinil 200 Australia",
    price: "$85.00 - $800.00",
    image: "../images/Modafinil/Modalert-200mg-300x250.webp",
    ingredient: "Modafinil",
    manufacturer: "Medicare Remedies",
    indication: "Cognitive Enhancers",
    strength: "200mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "modafinil",
    rating: 4.6,
    reviews: 31,
    prescription: true
},

{
    id: "Modasmart 400 MG",
    name: "Modasmart 400 MG",
    price: "$100.00 - $520.00",
    image: "../images/Modafinil/Modasmart-400-mg-200x167.webp",
    ingredient: "Modafinil",
    manufacturer: "Cephalon Inc.",
    indication: "Cognitive Enhancers",
    strength: "200mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "modafinil",
    rating: 4.9,
    reviews: 78,
    prescription: true
},

  {
    id: "Carisoprodol-350",
    name: "Carisoprodol 350 MG",
    price: "$70.00 - $245.00",
    image: "../images/painoSoma/carisoprodol-350mg-300x250.webp",
    ingredient: "Carisoprodol",
    manufacturer: "Wallace Pharmaceuticals",
    indication: "Muscle Relaxant",
    strength: "350mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "painosoma",
    rating: 4.8,
    reviews: 45,
    prescription: true
  },

  {
    id: "Pain-O-Soma-350",
    name: "Pain O Soma 350 MG",
    price: "$55.00 - $125.00",
    image: "../images/painoSoma/pain-o-Soma-300x250.webp",
    ingredient: "Carisoprodol",
    manufacturer: "Hab Pharma",
    indication: "Muscle Relaxant",
    strength: "350mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "painosoma",
    rating: 4.7,
    reviews: 39,
    prescription: true
  },

  {
    id: "Pain-O-Soma-500",
    name: "Pain O Soma 500 MG",
    price: "$50.00 - $280.00",
    image: "../images/painoSoma/pain-o-soma-500mg-300x250.webp",
    ingredient: "Carisoprodol",
    manufacturer: "Hab Pharma",
    indication: "Muscle Relaxant",
    strength: "500mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "painosoma",
    rating: 4.9,
    reviews: 58,
    prescription: true
  },

  {
    id: "Soma-Boost-1000",
    name: "Soma Boost 1000 MG",
    price: "$85.00 - $800.00",
    image: "../images/painoSoma/Soma-Boost-1000Mg-200x167.webp",
    ingredient: "Carisoprodol",
    manufacturer: "Steris Healthcare",
    indication: "Muscle Relaxant",
    strength: "1000mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "painosoma",
    rating: 4.9,
    reviews: 66,
    prescription: true
  },

  {
    id: "Soma-Boost-750",
    name: "Soma Boost 750 MG",
    price: "$100.00 - $520.00",
    image: "../images/painoSoma/Soma-Boost-750Mg-200x167.webp",
    ingredient: "Carisoprodol",
    manufacturer: "Steris Healthcare",
    indication: "Muscle Relaxant",
    strength: "750mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "painosoma",
    rating: 4.8,
    reviews: 51,
    prescription: true
  },

    {
    id: "Gabatop-100",
    name: "Gabapentin 100 MG",
    price: "$40.00 - $410.00",
    image: "../images/gabapentin/gabatop-100mg-300x250.webp",
    ingredient: "Gabapentin",
    manufacturer: "Healing Pharma",
    indication: "Neuropathic Pain",
    strength: "100mg",
    packaging: "10 Capsules in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "gabapentin",
    rating: 4.7,
    reviews: 41,
    prescription: true
  },

  {
    id: "Gabatop-300",
    name: "Gabapentin 300 MG",
    price: "$45.00 - $384.00",
    image: "../images/gabapentin/gabatop-300-300x250.webp",
    ingredient: "Gabapentin",
    manufacturer: "Healing Pharma",
    indication: "Neuropathic Pain",
    strength: "300mg",
    packaging: "10 Capsules in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "gabapentin",
    rating: 4.8,
    reviews: 53,
    prescription: true
  },

  {
    id: "Gabatop-400",
    name: "Gabapentin 400 MG",
    price: "$78.00 - $717.60",
    image: "../images/gabapentin/Gabatop-400-300x250.webp",
    ingredient: "Gabapentin",
    manufacturer: "Healing Pharma",
    indication: "Neuropathic Pain",
    strength: "400mg",
    packaging: "10 Capsules in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "gabapentin",
    rating: 4.9,
    reviews: 62,
    prescription: true
  },

  {
    id: "Gabatop-600",
    name: "Gabapentin 600 MG",
    price: "$50.00 - $599.00",
    image: "../images/gabapentin/Gabatop-600-300x250.webp",
    ingredient: "Gabapentin",
    manufacturer: "Healing Pharma",
    indication: "Neuropathic Pain",
    strength: "600mg",
    packaging: "10 Capsules in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "gabapentin",
    rating: 4.8,
    reviews: 56,
    prescription: true
  },

  {
    id: "Gabatop-800",
    name: "Gabapentin 800 MG",
    price: "$70.00 - $625.00",
    image: "../images/gabapentin/gabatop-800-300x250.webp",
    ingredient: "Gabapentin",
    manufacturer: "Healing Pharma",
    indication: "Neuropathic Pain",
    strength: "800mg",
    packaging: "10 Capsules in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "gabapentin",
    rating: 4.9,
    reviews: 68,
    prescription: true
  },

  {
    id: "Smartfinil-200",
    name: "Smartfinil 200 MG",
    price: "$60.00 - $370.00",
    image: "../images/selling products/Smartfinil-200mg-1-200x167.webp",
    ingredient: "Modafinil",
    manufacturer: "Healing Pharma",
    indication: "Cognitive Enhancers",
    strength: "200mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "modafinil",
    rating: 4.9,
    reviews: 84,
    prescription: true,
    bestSelling: true
},

{
    id: "Kamagra-Oral-Jelly",
    name: "Kamagra Oral Jelly Australia",
    price: "$55.00 - $125.00",
    image: "../images/selling products/Kamagra-Oral-Jelly-Australia-200x167.webp",
    ingredient: "Sildenafil Citrate",
    manufacturer: "Ajanta Pharma",
    indication: "Erectile Dysfunction",
    strength: "100mg",
    packaging: "7 Sachets in 1 Box",
    deliveryTime: "6 To 15 days",
    category: "erectiledysfunction",
    rating: 4.8,
    reviews: 76,
    prescription: true,
    bestSelling: true
},


{
    id: "Smartfinil-400",
    name: "Smartfinil 400 MG",
    price: "$90.00 - $470.00",
    image: "../images/selling products/Smartfinil-400mg-200x167.webp",
    ingredient: "Modafinil",
    manufacturer: "Healing Pharma",
    indication: "Cognitive Enhancers",
    strength: "400mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "modafinil",
    rating: 4.9,
    reviews: 91,
    prescription: true,
    bestSelling: true
},

{
    id: "Modalert-200",
    name: "Buy Modalert 200 MG",
    price: "$60.00 - $370.00",
    image: "../images/selling products/modalert-300x250.webp",
    ingredient: "Modafinil",
    manufacturer: "Sun Pharma",
    indication: "Cognitive Enhancers",
    strength: "200mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "modafinil",
    rating: 5.0,
    reviews: 112,
    prescription: true,
    bestSelling: true
},

{
    id: "Lovento-Black-200",
    name: "Lovento Black 200 MG",
    price: "$113.00 - $279.00",
    image: "../images/tranding-products/Lovento-Black-200-Mg-200x167.webp",
    ingredient: "Sildenafil Citrate",
    manufacturer: "Actiza Pharmaceutical Pvt. Ltd.",
    indication: "Erectile Dysfunction",
    strength: "200mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "erectile-dysfunction",
    rating: 4.9,
    reviews: 72,
    prescription: true,
    trendingProduct: true
  },

  {
    id: "Super-Lovento",
    name: "Super Lovento",
    price: "$60.00 - $360.00",
    image: "../images/tranding-products/Super-Lovento-200x167.webp",
    ingredient: "Sildenafil + Dapoxetine",
    manufacturer: "Actiza Pharmaceutical Pvt. Ltd.",
    indication: "Erectile Dysfunction & Premature Ejaculation",
    strength: "100mg + 60mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "erectile-dysfunction",
    rating: 4.8,
    reviews: 64,
    prescription: true,
    trendingProduct: true
  },

  {
    id: "Lovento-Oral-Jelly-100",
    name: "Lovento Oral Jelly 100 MG",
    price: "$55.00 - $240.00",
    image: "../images/tranding-products/Lovento-Oral-Jelly-all-Flavour-200x167.webp",
    ingredient: "Sildenafil Citrate",
    manufacturer: "Actiza Pharmaceutical Pvt. Ltd.",
    indication: "Erectile Dysfunction",
    strength: "100mg",
    packaging: "7 Sachets in 1 Box",
    deliveryTime: "6 To 15 days",
    category: "erectile-dysfunction",
    rating: 4.7,
    reviews: 51,
    prescription: true,
    trendingProduct: true
  },

  {
    id: "Lovento-100",
    name: "Lovento 100 MG",
    price: "$70.00 - $480.00",
    image: "../images/tranding-products/Lovento-200x167.webp",
    ingredient: "Sildenafil Citrate",
    manufacturer: "Actiza Pharmaceutical Pvt. Ltd.",
    indication: "Erectile Dysfunction",
    strength: "100mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "erectile-dysfunction",
    rating: 4.8,
    reviews: 58,
    prescription: true,
    trendingProduct: true
  },

  {
    id: "Actilis-20",
    name: "Actilis 20 MG",
    price: "$84.00 - $286.00",
    image: "../images/tranding-products/Actilis-20mg-200x167.webp",
    ingredient: "Tadalafil",
    manufacturer: "Actiza Pharmaceutical Pvt. Ltd.",
    indication: "Erectile Dysfunction",
    strength: "20mg",
    packaging: "10 Tablets in 1 Strip",
    deliveryTime: "6 To 15 days",
    category: "erectile-dysfunction",
    rating: 4.9,
    reviews: 69,
    prescription: true,
    trendingProduct: true
  },

  {
  id: "Nappie-7.5",
  name: "Nappie 7.5 MG",
  price: "$50.00 - $280.00",
  image: "../images/Zopiclone/Nappie-200x167 (1).webp",
  ingredient: "Zopiclone",
  manufacturer: "Actiza Pharmaceutical Pvt. Ltd.",
  indication: "Insomnia",
  strength: "7.5mg",
  packaging: "10 Tablets in 1 Strip",
  deliveryTime: "6 To 15 days",
  category: "zopiclone",
  rating: 4.8,
  reviews: 46,
  prescription: true
},

{
  id: "Nappie-10",
  name: "Nappie 10 MG",
  price: "$55.00 - $320.00",
  image: "../images/Zopiclone/Zopiclone-20-Mg-200x167.webp",
  ingredient: "Zopiclone",
  manufacturer: "Actiza Pharmaceutical Pvt. Ltd.",
  indication: "Insomnia",
  strength: "10mg",
  packaging: "10 Tablets in 1 Strip",
  deliveryTime: "6 To 15 days",
  category: "zopiclone",
  rating: 4.7,
  reviews: 39,
  prescription: true
},

{
  id: "Zopimax-7.5",
  name: "Zopimax 7.5 MG",
  price: "$48.00 - $290.00",
  image: "../images/Zopiclone/Zopicon-7.5Mg-200x167.webp",
  ingredient: "Zopiclone",
  manufacturer: "Healing Pharma",
  indication: "Insomnia",
  strength: "7.5mg",
  packaging: "10 Tablets in 1 Strip",
  deliveryTime: "6 To 15 days",
  category: "zopiclone",
  rating: 4.8,
  reviews: 52,
  prescription: true
},

{
  id: "Zopiclone-10",
  name: "Zopiclone 10 MG",
  price: "$60.00 - $355.00",
  image: "../images/Zopiclone/Zopifresh-7.5Mg-200x167.webp",
  ingredient: "Zopiclone",
  manufacturer: "Sun Pharma",
  indication: "Insomnia",
  strength: "10mg",
  packaging: "10 Tablets in 1 Strip",
  deliveryTime: "6 To 15 days",
  category: "zopiclone",
  rating: 4.9,
  reviews: 61,
  prescription: true
},

{
  id: "Zopisign-7.5",
  name: "Zopisign 7.5 MG",
  price: "$52.00 - $340.00",
  image: "../images/Zopiclone/zopisign-10mg-1-300x250.webp",
  ingredient: "Zopiclone",
  manufacturer: "Hab Pharma",
  indication: "Insomnia",
  strength: "7.5mg",
  packaging: "10 Tablets in 1 Strip",
  deliveryTime: "6 To 15 days",
  category: "zopiclone",
  rating: 4.8,
  reviews: 57,
  prescription: true
},
{
  id: "Aspadol-100-mg-(Tapentadol)",
  name: "Aspadol 100 mg (Tapentadol)",
  price: "$52.00 - $340.00",
  image: "../images/gabapentin/pain.webp",
  ingredient: "Zopiclone",
  manufacturer: "Hab Pharma",
  indication: "Insomnia",
  strength: "7.5mg",
  packaging: "10 Tablets in 1 Strip",
  deliveryTime: "6 To 15 days",
  category: "pain",
  rating: 4.8,
  reviews: 57,
  prescription: true
},

// blood suger 



// anesthesia
{
  id: "Anawin-0.5-INJ-(BUPIVACAINE)",
  name: "Anawin 0.5% INJ. (BUPIVACAINE)",
  price: "$35.00 - $180.00",
  image: "../images/anesthesia/anawin-200x167.webp",
  ingredient: "Bupivacaine",
  manufacturer: "Neon Laboratories",
  indication: "Local Anaesthesia",
  strength: "0.5%",
  packaging: "Vial",
  deliveryTime: "6 To 15 days",
  category: "Anaesthesia - Local",
  rating: 4.7,
  reviews: 42,
  prescription: true
},
{
  id: "Unwanted-Kit",
  name: "Unwanted Kit",
  price: "$55.00 - $120.00",
  image: "../images/anesthesia/Unwanted-Kit-200x167.webp",
  ingredient: "Mifepristone + Misoprostol",
  manufacturer: "Mankind Pharma",
  indication: "Medical Abortion",
  strength: "200mg + 200mcg",
  packaging: "1 Kit",
  deliveryTime: "6 To 15 days",
  category: "Anaesthesia - Local",
  rating: 4.8,
  reviews: 67,
  prescription: true
},
{
  id: "Fapivir-200-mg",
  name: "Fapivir 200 mg",
  price: "$45.00 - $220.00",
  image: "../images/anesthesia/Fapivir-200Mg-200x167.webp",
  ingredient: "Favipiravir",
  manufacturer: "Zydus Cadila",
  indication: "Antiviral",
  strength: "200mg",
  packaging: "34 Tablets",
  deliveryTime: "6 To 15 days",
  category: "Anaesthesia - Local",
  rating: 4.6,
  reviews: 38,
  prescription: true
},
{
  id: "Nizonide-DT-200-mg-(Nitazoxanide)",
  name: "Nizonide DT 200 mg (Nitazoxanide)",
  price: "$28.00 - $135.00",
  image: "../images/anesthesia/Nizonide-DT-200Mg-200x167.webp",
  ingredient: "Nitazoxanide",
  manufacturer: "Lupin Ltd.",
  indication: "Antiparasitic",
  strength: "200mg",
  packaging: "10 Tablets in 1 Strip",
  deliveryTime: "6 To 15 days",
  category: "Anaesthesia - Local",
  rating: 4.7,
  reviews: 31,
  prescription: true
},
{
  id: "Berberine-500mg-Capsules",
  name: "Berberine 500mg Capsules",
  price: "$28.00 - $135.00",
  image: "../images/blood-sugar/berberine_500_2_11zon-200x167.jpg",
  ingredient: "Berberine",
  manufacturer: "Natural Supplements",
  indication: "Blood Sugar Support",
  strength: "500mg",
  packaging: "60 Capsules",
  deliveryTime: "6 To 15 days",
  category: "blood-sugar",
  rating: 4.8,
  reviews: 56,
  prescription: false
},
{
  id: "Ponatinib 45 mg (Lucipona)",
  name: "Ponatinib 45 mg (Lucipona)",
  price: "$220.00 - $1350.00",
  image: "../images/chronic-myeloid-leukemia/Lucipona-45Mg-1-200x167.webp",
  ingredient: "Ponatinib",
  manufacturer: "Lucius Pharmaceuticals",
  indication: "Chronic Myeloid Leukemia",
  strength: "45mg",
  packaging: "30 Tablets",
  deliveryTime: "6 To 15 days",
  category: "Chronic Myeloid Leukemia",
  rating: 4.8,
  reviews: 29,
  prescription: true
},
{
  id: "Lucipona 45 mg (Ponatinib)",
  name: "Lucipona 45 mg (Ponatinib)",
  price: "$220.00 - $1350.00",
  image: "../images/chronic-myeloid-leukemia/Lucipona-45Mg-1-200x167.webp",
  ingredient: "Ponatinib",
  manufacturer: "Lucius Pharmaceuticals",
  indication: "Chronic Myeloid Leukemia",
  strength: "45mg",
  packaging: "30 Tablets",
  deliveryTime: "6 To 15 days",
  category: "Chronic Myeloid Leukemia",
  rating: 4.8,
  reviews: 29,
  prescription: true
},
{
  id: "Ponatinib 15 mg (Lucipona)",
  name: "Ponatinib 15 mg (Lucipona)",
  price: "$120.00 - $720.00",
  image: "../images/chronic-myeloid-leukemia/Lucipona-15Mg-1-200x167.webp",
  ingredient: "Ponatinib",
  manufacturer: "Lucius Pharmaceuticals",
  indication: "Chronic Myeloid Leukemia",
  strength: "15mg",
  packaging: "30 Tablets",
  deliveryTime: "6 To 15 days",
  category: "Chronic Myeloid Leukemia",
  rating: 4.7,
  reviews: 24,
  prescription: true
},
{
  id: "Lucipona 15 mg (Ponatinib)",
  name: "Lucipona 15 mg (Ponatinib)",
  price: "$120.00 - $720.00",
  image: "../images/chronic-myeloid-leukemia/Lucipona-15Mg-1-200x167.webp",
  ingredient: "Ponatinib",
  manufacturer: "Lucius Pharmaceuticals",
  indication: "Chronic Myeloid Leukemia",
  strength: "15mg",
  packaging: "30 Tablets",
  deliveryTime: "6 To 15 days",
  category: "Chronic Myeloid Leukemia",
  rating: 4.7,
  reviews: 24,
  prescription: true
},

];